### ISSUE TITLE
Missing Script?

### ISSUE THREAD

**Issue by ghost** [mdn/samples-server#107]
I was looking through the webRTC examples to see if I could use one as a template, and upon looking at `webrtc-simple-datachannel/index.html` there is a script mentioned called `../adapter.js`. Looks like it's missing. 

Is it not needed? What is it for?

**Comment by marius-turtle** [comment]
@F1nx 
I guess it is not necessary, at least for the [`webrtc-simple-datachannel`](https://github.com/mdn/samples-server/tree/master/s/webrtc-simple-datachannel)-example tested in Chrome version `87.0.4280`, but respective pull request is created. Another spot where `adapter.js` is referenced is in the [`webrtc-from-chat`](https://github.com/mdn/samples-server/tree/master/s/websocket-chat)-example, although it is included there directly in the example-directory. Will try to update the pull request to change that.

**Comment by marius-turtle** [comment]
Updated pull request #108  see 569c006
