### ISSUE TITLE
Sample site expired https certificate

### ISSUE THREAD

**Issue by leefreemanxyz** [mdn/samples-server#46]
Hello,

I'm aware this isn't strictly an issue with the code, but the security certificate for the [sample site](https://mdn-samples.mozilla.org/s/webrtc-from-chat/) expired yesterday (23 October) (so we get a 'NET::ERR_CERT_DATE_INVALID' error). 

Thanks
Lee

**Comment by jgmize** [comment]
Thanks @leefreemanxyz, this is now resolved: https://github.com/mdn/samples-server/pull/47#issuecomment-342379545
