### ISSUE TITLE
webrtc-capturestill/capture.js:43: "Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided."

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mdn/samples-server#63]
On Chromium. On Firefox no errors and no video.

**Comment by rickhoro** [comment]
According to https://stackoverflow.com/a/53821674, URL.createObjectURL has been deprecated in Google Chrome. Can be made to work, as follows:

```
video = document.getElementById('video');
navigator.getMedia(
      {
        video: true,
        audio: false
      },
      function(stream) {
        if (navigator.mozGetUserMedia) {
          video.mozSrcObject = stream;
        } else {
          var vendorURL = window.URL || window.webkitURL;
          video.srcObject = stream;
        }
        video.play();
      },
      function(err) {
        console.log("An error occured! " + err);
      }
    );
```

**Comment by kaymccormick** [comment]
This works for me. Main difference is appears to be the "video.srcObject = stream" line.

**Comment by a2sheppy** [comment]
The code no longer includes the createObjectURL(), which was left in place for a while while browsers caught up to the latest spec. Now that they're there, it was time to pull it.
