### ISSUE TITLE
Failed to execute 'createAnswer' on 'RTCOeerConnection' on the demo at glitch.me

### ISSUE THREAD

**Issue by rosacola** [mdn/samples-server#75]
> Error opening your camera and/or microphone: Failed to execute 'createAnswer' on 'RTCPeerConnection': PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer.

[https://webrtc-from-chat.glitch.me/](https://webrtc-from-chat.glitch.me/)
Error triggered when tried to initiate a video call between two clients; Chrome 72 on mac and Android.

**Comment by HirenOza** [comment]
@rosacola 
Is this issue resolved?
If yes could you please help me to solve it out.

Thanks

**Comment by rosacola** [comment]
@HirenOza sorry cannot help you I don't even remember creating this issue.
